### PR TITLE
set username and complete job type in the template

### PR DESCRIPTION
**Pull request by wenjie2wang**
Nice package, Yulia.

This is a simple PR that adds the three other job types and sets appropriate username.

### CODE REVIEW

**Comment by wenjie2wang** [comment]
I realized that there should probably be a new argument for `username` if `build_template` is used locally.

**Comment by yonicd** [comment]
should i revert so you can update?

**Comment by wenjie2wang** [comment]
I create a second PR.  Thanks.

**Comment by yuliasidi** [comment]
Thanks for your contribution!

**Pull request merged**
